#!/bin/bash

MEMORY=$((1024 * 1024 * 1024 * 32)) # 32 GiB
CPU=$((16 * 100000)) # 16 CPUs (quota in microseconds per 100ms period)

while true
do
  for CONTAINER in $(docker ps -aq)
  do
    OUTPUT=$(docker inspect --format="{{.Id}} {{.Name}} {{.HostConfig.CpuQuota}} {{.HostConfig.Memory}} {{.HostConfig.MemorySwap}}" "$CONTAINER" | grep -E "_build|_system_docker")
    [ -z "$OUTPUT" ] && continue
    ID=$(echo "$OUTPUT" | awk '{print $1}')
    NAME=$(echo "$OUTPUT" | awk '{print $2}')
    CURRENT_CPU=$(echo "$OUTPUT" | awk '{print $3}')
    CURRENT_MEMORY=$(echo "$OUTPUT" | awk '{print $4}')
    if [ "$CURRENT_CPU" != "$CPU" ]; then
      echo "Found $NAME container with CPU quota: $CURRENT_CPU. Setting to $CPU"
      docker update --cpu-quota=$CPU "$ID"
    fi
    if [ "$CURRENT_MEMORY" != "$MEMORY" ]; then
      echo "Found $NAME container with Memory limit: $CURRENT_MEMORY. Setting to $MEMORY"
      docker update --memory="$MEMORY" --memory-swap="$MEMORY" "$ID"
    fi
  done
  sleep 10
done
